### ISSUE TITLE
TODO before/after merging PR(https://github.com/Nitrokey/nitrokey-documentation/pull/272)

### ISSUE THREAD

**Issue by Keksmo** [Nitrokey/nitrokey-documentation#276]
- [ ] find a solution to use toctrees for the features list on the index pages of the nitrokeys
- [ ] delete/edit some outdated articles, which are now duplicates of other articles (or duplicates of sections of other articles)
- [ ] fix translation
- [ ] test redirects (especially difference between the 2fa files for FIDO, U2F and TOTP because original files had very similar naming
- [ ] shorten some file names (i.e. openpgp files)
- [ ] replace product names with generic names (i.e. Nitrokey instead of Nitrokey FIDO2) in Feature pages when there is more than one product the article applies to

**Comment by daringer** [comment]
closed in favor of: https://github.com/Nitrokey/nitrokey-documentation/issues/359
